server:
  servlet:
    context-path: /sell
  port: 8080



spring:
  profiles:
    active: dev
  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1/sell?useSSL=false&serverTimeZone=UTC&useOldAliasMetadataBehavior=true
    username: root
    password: 335100
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  freemarker:
    suffix: .ftl

#定义网址
project-url:
  sell: localhost:8080

